"""
Stage 1 - HDR Light Map Estimation & EXR Converter
Author: Ratish (Person A - AI & Data Pipeline)

Converts 8-bit LDR background plates or 360 panoramas into 32-bit floating point 
.exr environment maps by isolating key light sources and boosting high-luminance peaks.
"""

import os
import argparse
import numpy as np
import cv2


def convert_ldr_to_hdr_exr(
    input_image_path: str,
    output_exr_path: str,
    depth_path: str = None,
    sun_boost: float = 15.0,
):
    """
    Converts an LDR image into an approximate HDR environment map.

    Parameters
    ----------
    input_image_path : str
        Input background image (.png/.jpg)

    output_exr_path : str
        Output HDRI (.exr)

    depth_path : str, optional
        Depth map generated by estimate_depth.py.
        Reserved for future HDR improvements.

    sun_boost : float
        Bright light intensity multiplier.
    """

    print(f"[HDR Estimator] Processing: {input_image_path}")

    if not os.path.exists(input_image_path):
        raise FileNotFoundError(input_image_path)

    img = cv2.imread(input_image_path, cv2.IMREAD_COLOR)

    if img is None:
        raise ValueError(f"Unable to read image: {input_image_path}")

    # -------------------------------------------------------
    # Optional depth map
    # -------------------------------------------------------

    depth = None

    if depth_path:

        if os.path.exists(depth_path):

            print(f"[HDR Estimator] Using depth map: {depth_path}")

            depth = cv2.imread(depth_path, cv2.IMREAD_GRAYSCALE)

            if depth is not None:
                depth = depth.astype(np.float32) / 255.0

        else:

            print("[HDR Estimator] Warning: Depth map not found. Continuing...")

    # -------------------------------------------------------
    # Convert to linear color space
    # -------------------------------------------------------

    img_float = img.astype(np.float32) / 255.0

    img_linear = np.power(img_float, 2.2)

    # -------------------------------------------------------
    # Luminance
    # -------------------------------------------------------

    luminance = (
        0.2126 * img_linear[:, :, 2]
        + 0.7152 * img_linear[:, :, 1]
        + 0.0722 * img_linear[:, :, 0]
    )

    threshold = np.percentile(luminance, 95)

    bright_mask = np.maximum(
        0.0,
        (luminance - threshold) / (1.0 - threshold + 1e-5),
    )

    # -------------------------------------------------------
    # Optional depth weighting
    # -------------------------------------------------------

    if depth is not None:

        # Give slightly more importance to distant bright regions
        # (usually sky / sun)

        bright_mask = bright_mask * (0.5 + 0.5 * (1.0 - depth))

    bright_mask = np.clip(bright_mask, 0.0, 1.0)

    bright_mask_3ch = np.dstack(
        [
            bright_mask,
            bright_mask,
            bright_mask,
        ]
    )

    # -------------------------------------------------------
    # HDR approximation
    # -------------------------------------------------------

    hdr_map = img_linear + (
        img_linear * bright_mask_3ch * sun_boost
    )

    hdr_map = hdr_map.astype(np.float32)

    os.makedirs(os.path.dirname(output_exr_path), exist_ok=True)

    try:

        import imageio.v3 as iio

        iio.imwrite(output_exr_path, hdr_map)

        print(f"[HDR Estimator] EXR saved: {output_exr_path}")

    except Exception as e:

        print(f"[HDR Estimator] EXR export failed: {e}")

        fallback = output_exr_path.replace(".exr", ".hdr")

        cv2.imwrite(fallback, hdr_map)

        print(f"[HDR Estimator] HDR saved: {fallback}")

    return output_exr_path


def main():

    parser = argparse.ArgumentParser(
        description="LDR to HDR Environment Map Converter"
    )

    parser.add_argument(
        "--input",
        required=True,
        help="Input background image",
    )

    parser.add_argument(
        "--depth",
        required=False,
        default=None,
        help="Optional depth map",
    )

    parser.add_argument(
        "--output",
        required=True,
        help="Output EXR/HDR file",
    )

    parser.add_argument(
        "--boost",
        type=float,
        default=15.0,
        help="Sun intensity multiplier",
    )

    args = parser.parse_args()

    convert_ldr_to_hdr_exr(
        args.input,
        args.output,
        args.depth,
        args.boost,
    )


if __name__ == "__main__":
    main()