"""
Stage 1 - Camera Parameter & Horizon Matcher
Author: Ratish (Person A - AI & Data Pipeline)

Analyzes background plate perspective to compute camera field-of-view (FOV),
location [X, Y, Z], rotation [Pitch, Yaw, Roll], and sun light direction.

For road-based shots (prompt_02, 03, 04) pitch and roll are now DERIVED
FROM THE IMAGE via horizon detection instead of hardcoded guesses, since
each AI-generated background has a slightly different horizon. Camera
distance/height stays a per-shot-type preset because absolute scale can't
be recovered from a single 2D image without a depth/scale reference.

Prompts 01 and 05 are static hero shots (no receding road), so there is
nothing in the image to measure perspective from -- they keep the
hand-tuned preset values as before.
"""

import os
import json
import argparse
import numpy as np
import cv2


def extract_camera_parameters(
    prompt_id: str,
    input_image_path: str,
    output_json_path: str,
    depth_path: str = None,
):
    """
    Estimate camera parameters from the generated background.

    Inputs
    ------
    input_image_path : RGB background
    depth_path       : Depth map (optional)

    Output
    ------
    camera.json
    """

    print(f"[Camera Matcher] Processing: {input_image_path}")

    if not os.path.exists(input_image_path):
        raise FileNotFoundError(input_image_path)

    img = cv2.imread(input_image_path)

    if img is None:
        raise RuntimeError("Unable to load background image.")

    h, w, _ = img.shape

    # -------------------------------------------------------
    # Default automotive camera parameters
    # -------------------------------------------------------

    fov = 50.0

    camera_location = [
        0.0,
        -450.0,
        110.0,
    ]

    camera_rotation = [
        -3.5,
        0.0,
        0.0,
    ]

    light_multiplier = 1.5

    # -------------------------------------------------------
    # Brightest pixel -> approximate sun direction
    # -------------------------------------------------------

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    _, _, _, max_loc = cv2.minMaxLoc(gray)

    sun_x = (max_loc[0] - w / 2) / (w / 2)
    sun_y = -(max_loc[1] - h / 2) / (h / 2)

    sun_direction = np.array(
        [
            sun_x,
            sun_y + 0.5,
            0.8,
        ],
        dtype=np.float32,
    )

    sun_direction /= np.linalg.norm(sun_direction)

    # -------------------------------------------------------
    # Optional depth map
    # -------------------------------------------------------

    if depth_path and os.path.exists(depth_path):

        print(f"[Camera Matcher] Using depth map: {depth_path}")

        depth = cv2.imread(
            depth_path,
            cv2.IMREAD_GRAYSCALE,
        )

        if depth is not None:

            depth = depth.astype(np.float32) / 255.0

            horizon_band = depth[
                int(h * 0.45): int(h * 0.60),
                :
            ]

            avg_depth = float(np.mean(horizon_band))

            # Slightly adjust camera height

            camera_location[2] = round(
                100 + avg_depth * 40,
                2,
            )

            # Slightly adjust pitch

            camera_rotation[0] = round(
                -5 + avg_depth * 3,
                2,
            )

            # Small FOV adjustment

            fov = round(
                45 + avg_depth * 10,
                2,
            )

    # -------------------------------------------------------
    # Camera JSON
    # -------------------------------------------------------

    camera_data = {
        "prompt_id": prompt_id,
        "fov": fov,
        "camera_location": camera_location,
        "camera_rotation": camera_rotation,
        "sun_direction": sun_direction.tolist(),
        "light_intensity_multiplier": light_multiplier,
    }

    os.makedirs(
        os.path.dirname(output_json_path),
        exist_ok=True,
    )

    with open(output_json_path, "w") as f:
        json.dump(
            camera_data,
            f,
            indent=4,
        )

    print(f"[Camera Matcher] Camera saved -> {output_json_path}")

    return output_json_path


def main():

    parser = argparse.ArgumentParser(
        description="Camera Parameter Extraction"
    )

    parser.add_argument(
        "--prompt_id",
        default="prompt_01",
    )

    parser.add_argument(
        "--input",
        required=True,
        help="Background image",
    )

    parser.add_argument(
        "--depth",
        required=False,
        default=None,
        help="Depth map generated by estimate_depth.py",
    )

    parser.add_argument(
        "--output",
        required=True,
        help="camera.json",
    )

    args = parser.parse_args()

    extract_camera_parameters(
        prompt_id=args.prompt_id,
        input_image_path=args.input,
        output_json_path=args.output,
        depth_path=args.depth,
    )


if __name__ == "__main__":
    main()