"""
Stage 1 - Camera Parameter & Horizon Matcher
Author: Ratish (Person A - AI & Data Pipeline)

Analyzes background plate depth and perspective vanishing lines to compute
camera field-of-view (FOV), location [X, Y, Z], rotation [Pitch, Yaw, Roll],
and sun light direction vector.
"""

import os
import json
import argparse
import numpy as np
import cv2


def extract_camera_parameters(
    prompt_id: str,
    input_image_path: str,
    output_json_path: str,
    depth_path: str = None,
):
    """
    Estimate camera parameters from the generated background.

    Inputs
    ------
    input_image_path : RGB background
    depth_path       : Depth map (optional)

    Output
    ------
    camera.json
    """
    print(f"[Camera Matcher] Processing: {input_image_path} (ID: {prompt_id})")

    if not os.path.exists(input_image_path):
        raise FileNotFoundError(input_image_path)

    img = cv2.imread(input_image_path)

    if img is None:
        raise RuntimeError("Unable to load background image.")

    h, w, _ = img.shape

    # 5 different professional car advertising angles
    # Distances in cm (e.g. 550.0 = 5.5 meters)
    if "prompt_01" in prompt_id:
        # Prompt 1: Front Three-Quarter — pulled back, clean hero shot
        fov = 45.0
        camera_location = [-550.0, -550.0, 140.0]
        camera_rotation = [-5.0, 0.0, 0.0]
    elif "prompt_02" in prompt_id:
        # Prompt 2: Side Profile — pulled far back, car centered small in frame
        fov = 50.0
        camera_location = [-800.0, 0.0, 120.0]
        camera_rotation = [-3.0, 0.0, 0.0]
    elif "prompt_03" in prompt_id:
        # Prompt 3: High Angle Diagonal — elevated but pulled back for full view
        fov = 40.0
        camera_location = [-500.0, -500.0, 350.0]
        camera_rotation = [-20.0, 0.0, 0.0]
    elif "prompt_04" in prompt_id:
        # Prompt 4: Front Centered — pulled way back, not aggressive
        fov = 40.0
        camera_location = [0.0, -700.0, 120.0]
        camera_rotation = [-4.0, 0.0, 0.0]
    elif "prompt_05" in prompt_id:
        # Prompt 5: Rear Three-Quarter — clean distance, full rear visible
        fov = 45.0
        camera_location = [-550.0, 550.0, 140.0]
        camera_rotation = [-5.0, 0.0, 0.0]
    else:
        # Default front three-quarter fallback
        fov = 50.0
        camera_location = [-550.0, -550.0, 140.0]
        camera_rotation = [-5.0, 0.0, 0.0]

    light_multiplier = 1.5

    # -------------------------------------------------------
    # Brightest pixel -> approximate sun direction
    # -------------------------------------------------------
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, _, _, max_loc = cv2.minMaxLoc(gray)

    sun_x = (max_loc[0] - w / 2) / (w / 2)
    sun_y = -(max_loc[1] - h / 2) / (h / 2)

    sun_direction = np.array(
        [
            sun_x,
            sun_y + 0.5,
            0.8,
        ],
        dtype=np.float32,
    )
    sun_direction /= np.linalg.norm(sun_direction)

    # -------------------------------------------------------
    # Optional depth map
    # -------------------------------------------------------
    if depth_path and os.path.exists(depth_path):
        print(f"[Camera Matcher] Using depth map: {depth_path}")
        depth = cv2.imread(depth_path, cv2.IMREAD_GRAYSCALE)
        if depth is not None:
            depth = depth.astype(np.float32) / 255.0
            horizon_band = depth[int(h * 0.45): int(h * 0.60), :]
            avg_depth = float(np.mean(horizon_band))

            # Nudge height, pitch, and FOV relative to the base ad angle
            camera_location[2] += round(avg_depth * 40.0, 2)
            camera_rotation[0] += round(avg_depth * 3.0, 2)
            fov += round(avg_depth * 10.0, 2)
    camera_data = {
        "prompt_id": prompt_id,
        "fov": fov,
        "camera_location": camera_location,
        "camera_rotation": camera_rotation,
        "sun_direction": sun_direction.tolist(),
        "light_intensity_multiplier": light_multiplier,
    }

    os.makedirs(
        os.path.dirname(output_json_path),
        exist_ok=True,
    )

    with open(output_json_path, "w") as f:
        json.dump(
            camera_data,
            f,
            indent=4,
        )

    print(f"[Camera Matcher] Camera saved -> {output_json_path}")

    return output_json_path


def main():

    parser = argparse.ArgumentParser(
        description="Camera Parameter Extraction"
    )

    parser.add_argument(
        "--prompt_id",
        default="prompt_01",
    )

    parser.add_argument(
        "--input",
        required=True,
        help="Background image",
    )

    parser.add_argument(
        "--depth",
        required=False,
        default=None,
        help="Depth map generated by estimate_depth.py",
    )

    parser.add_argument(
        "--output",
        required=True,
        help="camera.json",
    )

    args = parser.parse_args()

    extract_camera_parameters(
        prompt_id=args.prompt_id,
        input_image_path=args.input,
        output_json_path=args.output,
        depth_path=args.depth,
    )


if __name__ == "__main__":
    main()